# DEVELOPMENT properties

# http connector properties
http:
  host: "0.0.0.0"
  port: "7081"
  
# american api connector properties
american:
  host: "proxy-ruk-american-flights-api.us-e2.cloudhub.io"
  port: "80"
  basePath: "/"
  protocol: "HTTP"
  client_id: "2dd84d88b0824527aa6c06533a94c92b"
  client_secret: "98811A1Ad52D4ce1B60BCD49859ec26a"
  
# united http request propererties
united:
  url: "http://mu.learn.mulesoft.com/united/flights/{code}"

# delta connector properties
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort-xxx"
  address: "http://ilt.learn.mulesoft.com/delta"