# TESTING properties

# http connector properties
http:
  host: "0.0.0.0"
  port: "9081"
    
# american api connector properties
american:
  host: "american-flights-api-proxy-ruk.us-e2.cloudhub.io"
  port: "80"
  basePath: "/"
  protocol: "HTTP"