# PRODUCTION properties

# http connector properties
http:
  host: "0.0.0.0"
  port: "8081"
    
# american api connector properties
american:
  host: "american-flights-api-proxy-ruk.us-e2.cloudhub.io"
  port: "80"
  basePath: "/"
  protocol: "HTTP"
  client_id: "cefc67c911eb422486c1041988f1141c"
  client_secret: "6Fe53eBaD91F419BAe47E81E146c2653"
  
# united http request propererties
united:
  url: "http://mu.learn.mulesoft.com/united/flights/{code}"